let Water = [
    {"id": "Aare", "level": "leicht", "name": "Aare", "artikel": "die"},
    {"id": "Emme", "level": "leicht", "name": "Emme", "artikel": "die"},
    {"id": "Thunersee", "level": "leicht", "name": "Thunersee", "artikel": "den"},
    {"id": "Brienzersee", "level": "leicht", "name": "Brienzersee", "artikel": "den"},
    {"id": "Wohlensee", "level": "leicht", "name": "Wohlensee", "artikel": "den"},
    {"id": "Bielersee", "level": "leicht", "name": "Bielersee", "artikel": "den"},
    {"id": "Simme", "level": "leicht", "name": "Simme", "artikel": "die"},
    {"id": "Kander", "level": "leicht", "name": "Kander", "artikel": "die"},
    {"id": "Schwarzwasser", "level": "mittel", "name": "Schwarzwasser", "artikel": "das"},
    {"id": "Saane", "level": "mittel", "name": "Saane", "artikel": "die"},
    {"id": "Sense", "level": "mittel", "name": "Sense", "artikel": "die"},
    {"id": "Gürbe", "level": "mittel", "name": "Gürbe", "artikel": "die"},
    {"id": "Ilfis", "level": "mittel", "name": "Ilfis", "artikel": "die"},
    {"id": "Zulg", "level": "mittel", "name": "Zulg", "artikel": "die"},
    {"id": "Grimselsee", "level": "mittel", "name": "Grimselsee", "artikel": "den"},
    {"id": "Oeschinensee", "level": "mittel", "name": "Oeschinensee", "artikel": "den"},
    {"id": "Engstlige", "level": "schwierig", "name": "Engstlige", "artikel": "die"},
    {"id": "Grüene", "level": "schwierig", "name": "Grüene", "artikel": "die"},
    {"id": "Birs", "level": "schwierig", "name": "Birs", "artikel": "die"},
    {"id": "SchwarzeLütschine", "level": "schwierig", "name": "Schwarze Lütschine", "artikel": "die"},
    {"id": "Trub", "level": "schwierig", "name": "Trub", "artikel": "die"},
    {"id": "Gadmerwasser", "level": "mittel", "name": "Gadmerwasser", "artikel": "das"},
    {"id": "Urbach", "level": "schwierig", "name": "Urbach", "artikel": "den"},
    {"id": "Narenbach", "level": "schwierig", "name": "Narenbach", "artikel": "den"},
    {"id": "Langete", "level": "mittel", "name": "Langete", "artikel": "die"},
    {"id": "WeisseLütschine", "level": "nichts", "name": "Weisse Lütschine", "artikel": "die"},
    {"id": "Gäntelwasser", "level": "schwierig", "name": "Gäntelwasser", "artikel": "das"},
    {"id": "Fildrich", "level": "mittel", "name": "Fildrich", "artikel": "den"},
    {"id": "Färmelbach", "level": "nichts", "name": "Färmelbach", "artikel": "den"},
    {"id": "Louibach", "level": "schwierig", "name": "Louibach", "artikel": "den"},
    {"id": "Kiese", "level": "mittel", "name": "Kiese", "artikel": "die"},
    {"id": "Hagneck-Kanal", "level": "nichts", "name": "Hagneck-Kanal", "artikel": "den"},
    {"id": "Nidau-Büren-Kanal", "level": "nichts", "name": "Nidau-Büren-Kanal", "artikel": "den"},
    {"id": "Schüss", "level": "nichts", "name": "Schüss", "artikel": "die"},
    {"id": "Scheulte", "level": "nichts", "name": "Scheltenbach", "artikel": "den"},
    {"id": "Zihlkanal", "level": "schwierig", "name": "Zihlkanal", "artikel": "den"},
    {"id": "Oberaarsee", "level": "nichts", "name": "Oberaarsee", "artikel": "den"},
    {"id": "Räterichsbodensee", "level": "nichts", "name": "Räterichsbodensee", "artikel": "den"},
    {"id": "Gelmersee", "level": "nichts", "name": "Gelmersee", "artikel": "den"},
    {"id": "Engstlensee", "level": "nichts", "name": "Engstlensee", "artikel": "den"},
    {"id": "Lütschine", "level": "nichts", "name": "Lütschine", "artikel": "die"},
    {"id": "Schiffenensee", "level": "nichts", "name": "Schiffenensee", "artikel": "der"},
    {"id": "Greyerzersee", "level": "nichts", "name": "Lac de la Gruyère", "artikel": "der"}
];
export default Water